version: '3.8'
services:
  orchestrator:
    build:
      context: .
      dockerfile: build/orchestrator/Dockerfile
    ports:
      - '8080:8080' # Ставьте любой порт, какой хотите.
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=Vasya
      - DATABASE_PASSWORD=123456789
      - DATABASE_NAME=proba
      - MODE_CONSOLE=DEV #Необязательно. Можете посмотреть README
      - TIME_ADDITION_MS=100
      - TIME_SUBTRACTION_MS=100
      - TIME_MULTIPLICATIONS_MS=100
      - TIME_DIVISIONS_MS=100
      - WRITE_FILE=FALSE
      - JWT_SECRET=super_secret_key
    depends_on:
      postgres:
        condition: service_healthy
  agent:
    build:
      context: .
      dockerfile: build/agent/Dockerfile
    environment:
      - GRPC_HOST=orchestrator
      - COMPUTING_POWER=25 #Как пример. В Dockerfile ставится по умолчанию 2.
      - JWT_SECRET=super_secret_key
    depends_on:
    -  orchestrator
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=Vasya       # пользователь БД
      - POSTGRES_PASSWORD=123456789  # пароль
      - POSTGRES_DB=proba        # название БД
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Vasya -d proba"]
      interval: 5s
      timeout: 5s
      retries: 5

#volumes:
#  postgres_data: