// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/proto/orchestrator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=Operation,proto3" json:"Operation,omitempty"`
	Arg1          float64                `protobuf:"fixed64,3,opt,name=Arg1,proto3" json:"Arg1,omitempty"`
	Arg2          float64                `protobuf:"fixed64,4,opt,name=Arg2,proto3" json:"Arg2,omitempty"`
	OperationTime int64                  `protobuf:"varint,5,opt,name=OperationTime,proto3" json:"OperationTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Task) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Task) GetArg1() float64 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *Task) GetArg2() float64 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *Task) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

type TaskWithResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=Operation,proto3" json:"Operation,omitempty"`
	Arg1          float64                `protobuf:"fixed64,3,opt,name=Arg1,proto3" json:"Arg1,omitempty"`
	Arg2          float64                `protobuf:"fixed64,4,opt,name=Arg2,proto3" json:"Arg2,omitempty"`
	Result        float64                `protobuf:"fixed64,5,opt,name=Result,proto3" json:"Result,omitempty"`
	OperationTime int64                  `protobuf:"varint,6,opt,name=OperationTime,proto3" json:"OperationTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskWithResult) Reset() {
	*x = TaskWithResult{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskWithResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskWithResult) ProtoMessage() {}

func (x *TaskWithResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskWithResult.ProtoReflect.Descriptor instead.
func (*TaskWithResult) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *TaskWithResult) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TaskWithResult) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *TaskWithResult) GetArg1() float64 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *TaskWithResult) GetArg2() float64 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *TaskWithResult) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TaskWithResult) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

var File_api_proto_orchestrator_proto protoreflect.FileDescriptor

const file_api_proto_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/orchestrator.proto\"\x82\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x1c\n" +
	"\tOperation\x18\x02 \x01(\tR\tOperation\x12\x12\n" +
	"\x04Arg1\x18\x03 \x01(\x01R\x04Arg1\x12\x12\n" +
	"\x04Arg2\x18\x04 \x01(\x01R\x04Arg2\x12$\n" +
	"\rOperationTime\x18\x05 \x01(\x03R\rOperationTime\"\xa4\x01\n" +
	"\x0eTaskWithResult\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x1c\n" +
	"\tOperation\x18\x02 \x01(\tR\tOperation\x12\x12\n" +
	"\x04Arg1\x18\x03 \x01(\x01R\x04Arg1\x12\x12\n" +
	"\x04Arg2\x18\x04 \x01(\x01R\x04Arg2\x12\x16\n" +
	"\x06Result\x18\x05 \x01(\x01R\x06Result\x12$\n" +
	"\rOperationTime\x18\x06 \x01(\x03R\rOperationTime2:\n" +
	"\fOrchestrator\x12*\n" +
	"\fGiveTakeTask\x12\x0f.TaskWithResult\x1a\x05.Task(\x010\x01B>Z<github.com/Cool-Andrey/Calculating/pkg/proto/orchestrator;pbb\x06proto3"

var (
	file_api_proto_orchestrator_proto_rawDescOnce sync.Once
	file_api_proto_orchestrator_proto_rawDescData []byte
)

func file_api_proto_orchestrator_proto_rawDescGZIP() []byte {
	file_api_proto_orchestrator_proto_rawDescOnce.Do(func() {
		file_api_proto_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_orchestrator_proto_rawDesc), len(file_api_proto_orchestrator_proto_rawDesc)))
	})
	return file_api_proto_orchestrator_proto_rawDescData
}

var file_api_proto_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_orchestrator_proto_goTypes = []any{
	(*Task)(nil),           // 0: Task
	(*TaskWithResult)(nil), // 1: TaskWithResult
}
var file_api_proto_orchestrator_proto_depIdxs = []int32{
	1, // 0: Orchestrator.GiveTakeTask:input_type -> TaskWithResult
	0, // 1: Orchestrator.GiveTakeTask:output_type -> Task
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_orchestrator_proto_init() }
func file_api_proto_orchestrator_proto_init() {
	if File_api_proto_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_orchestrator_proto_rawDesc), len(file_api_proto_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_orchestrator_proto_goTypes,
		DependencyIndexes: file_api_proto_orchestrator_proto_depIdxs,
		MessageInfos:      file_api_proto_orchestrator_proto_msgTypes,
	}.Build()
	File_api_proto_orchestrator_proto = out.File
	file_api_proto_orchestrator_proto_goTypes = nil
	file_api_proto_orchestrator_proto_depIdxs = nil
}
